### ISSUE TITLE
Error in Config value label:bug 

### ISSUE THREAD

**Issue by SM-26** [rkoe/mkdocs-emailprotect#1]
Hey,

I'm using MkDocs (on [gitlab](https://gitlab.com/SM26/swm_wiki)) and after adding
`pip install git+https://github.com/rkoe/mkdocs-emailprotect`
to my  .gitlab-ci.ylm

and
`  - emailprotect`
to my Mkdocs.yml

I get this error:
> ERROR   -  Config value: 'markdown_extensions'. Error: Failed to initiate extension 'emailprotect': module 'emailprotect' has no attribute 'makeExtension' 

Any ideas?

**Comment by rkoe** [comment]
Have you listed `- emailprotect` under markdownExtensions or under plugins?
It must be under plugins.

See also: https://github.com/mprivat/mkdocs-snippet-plugin/issues/1

If this does not help:
- Does the included test work?
- Can you send me your mkdocs.yaml, so I can test/verify it?

**Comment by SM-26** [comment]
damn, you are so right.
it was right in front of me!

now it's under Plugins and it works!
I think?
how can I make sure?
because right now it looks like plain text to me:
![image](https://user-images.githubusercontent.com/39513660/72742926-5b968f80-3bb3-11ea-8349-e6c94c8b5391.png)


Full code is here:
https://gitlab.com/SM26/swm_wiki

outcome is displayed here:
https://sm26.gitlab.io/swm_wiki/contribute/

this is what behind the contribute page:
```

You can reach me at my [E-mail](mailto:Gaist.Or+SWM@gmail.com)
[mail@example.com](mailto:mail@example.com)
<mailto:mail@example.com>
<mail@example.com>
```


I would assume that in the page inspect (<kbd>CTRL</kbd><kbd>Shift</kbd><kbd>I</kbd>) would see something like this:
`%u0071%u0065%u0073%u0083%u0084%u0079%u0082%u0071%u0077%u0065%u0073%u0076%u0067%u0079%u0077`



Thanks in advance

**Comment by rkoe** [comment]
It does work. Use "View Page Source" (in the right-click-menu) or wget to get the real html-code.

Firefox page inspect already converts the character references back to the characters, so you cannot see it there.
